accounts:
  - name: alice
    coins: ["200000000umis"]
  - name: bob
    coins: ["100000000umis"]
validator:
  name: alice
  staked: "100000000umis"
client:
  vuex:
    path: "vue/src/store/mises-store"
  openapi:
    path: "docs/static/openapi.yml"
faucet:
  name: bob
  coins: ["100000umis"]
build:
  binary: "misestmd"
init:
  app:
    minimum-gas-prices: "1umis"
    api:
      swagger: true
