# This is a basic workflow that is manually triggered

name: misestm

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on: [pull_request]

# This workflow makes x86_64 binaries for mac, windows, and linux.

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        arch: [amd64]
        targetos: [linux]
        #arch: [amd64, arm64]
        #targetos: [windows, darwin, linux]
    name: misestm ${{ matrix.arch }} for ${{ matrix.targetos }}
    steps:
      - uses: actions/checkout@v2
      - name: Setup go
        uses: actions/setup-go@v1
        with:
          go-version: 1.16
        env:
          GOOS: ${{ matrix.targetos }}
          GOARCH: ${{ matrix.arch }}

      - name: Compile
        run: |
          go mod download
          cd cmd/misestmd
          go build .
      - name: 'Tar files'
        run: |
          cd cmd/misestmd
          tar -czvf misestmd.tar.gz misestmd appspec.yml scripts/
      - uses: actions/upload-artifact@v2
        with:
          name: misestmd ${{ matrix.targetos }} ${{ matrix.arch }}
          path: cmd/misestmd/misestmd.tar.gz

  deploy:
    name: Deploy
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Download Artifact
        uses: actions/download-artifact@v2
        with:
          name: misestmd linux amd64
          path: build
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-2
      - name: Deploy to S3
        run: |
          aws s3 cp \
           --recursive \
           --region us-east-2 \
           ./build s3://misesid
      - name: CodeDeploy to EC2
        run: |
          aws deploy create-deployment \
           --application-name mises \
           --deployment-group-name MisesDeployGroup \
           --s3-location bucket=misesid,key=misestmd.tar.gz,bundleType=tgz

